Gdk/UnscaledDPI 152371
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Net/ThemeName "Breeze-Dark"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gtk/CursorThemeSize 37
Gtk/CursorThemeName "Simp1e-Gruvbox-Dark"
Net/SoundThemeName "ocean"
Net/IconThemeName "Gruvbox"
Gtk/FontName "Irix Screen Mono 15,  10"

